### ISSUE TITLE
عدم نمایش صحیح در برخی حروف چسبیده به هم

### ISSUE THREAD

**Issue by chalist** [rastikerdar/parastoo-font#10]
توی لیبره آفیس این مشکل پیش میاد

> Version: 5.1.2.2.0+
> Build ID: 5.1.2.2 Arch Linux build-1
> CPU Threads: 4; OS Version: Linux 4.5; UI Render: default; 
> Locale: en-US (en_US.UTF-8)

![shutter-selection_007](https://cloud.githubusercontent.com/assets/1072154/15386453/38fb90c8-1dbd-11e6-8f1d-5c76c9c60edf.png)

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو

نمی دونم دستگاه من مشکل داره یا نه ، آخه با فونت های دیگه هم تست می کنم توی لیبره آفیس همین مشکلو داره. هر بار هم باز می کنم رندوم روی حروف مختلف اینجوری میشه.
باز هم می گردم ببینم مشکلش چیه. اگر فونتی مدنظرتون هست که این مشکلو نداره بگین تا مقایسه کنم شاید مشکلشو پیدا کنم.

باز هم ممنونم

**Comment by behdad** [comment]
This is quite possibly a LibreOffice bug.  cc @khaledhosny

**Comment by khaledhosny** [comment]
The screenshot above? Yes, that is a known LibreOffice bug that is hard to crack.

**Comment by behdad** [comment]
What's the bug exactly?

**Comment by behdad** [comment]
Ie. what's the root cause?

**Comment by khaledhosny** [comment]
No one really knows, several people tried to fix it over the years and it always shows up again with different fonts. The real root issue is that the code that calculates kashida insertions and their number is fragile, split between several LibreOffice modules (like the rest of its text layout) and no one really understands it or have the time and interest to sort it out.

**Comment by rastikerdar** [comment]
پس من با اجازه ایشو رو می بندم.
آقای اسفهبد از شما ممنونم.
Thank you khaledhosny.

**Comment by rastikerdar** [comment]
این مشکل همچنان تو ذهنم بود تا اینکه فکر می کنم مشکل اون زائده ها در لیبره آفیس با نسخه جدید پرستو رفع شده باشه. دلیلش هم طولانی بودن گلیف تطویل بود که وقتی کوتاهش کردم مشکل برطرف شد.
![screenshot from 2016-11-11 01-26-25](https://cloud.githubusercontent.com/assets/3116038/20196050/35038d9c-a7ae-11e6-98b1-bf2d99a6cba5.png)

Tatweel Glyph.
با تشکر از آقای چالیست.

**Comment by khaledhosny** [comment]
The next version of LibreOffice should fix many of the kashida issues (I finally figured out how this is all implemented inside LibreOffice), but indeed a too long tatweel glyph can be problematic.

**Comment by rastikerdar** [comment]
Great news. LibreOffice is always my first choice. I understand how difficult it is to fix a chronic bug in this giant software. Thank you khaledhosny.
