### ISSUE TITLE
هماهنگی بین سوراخ‌ها

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/parastoo-font#2]
سوراخ‌ها اگر هماهنگ باشند خطای دید کمتری ایجاد میشه
الان سوراخی که تو ع وسط هست تو سایز ریز اصلا دیده نمیشه
برای شکل‌های مختلف ه ص م و اندازه‌های متفاوت داره که خوب نیست

**Comment by rastikerdar** [comment]
کاملا حق با شماست.
البته اندازه حالت ص ط همه یکی هست.
مشکل اینه که شکل های ه م هیچکدام شبیه به هم نیستند.
هر چند مـ ـمـ یکی هست اما بقیه بیشتر از نقطه نظر زیبایی طراحی شدند. باید دوباره بررسی کنم ببینم کدوم رو با کدوم ست کنم.

ممونم بابت گزارش خوبتون

**Comment by behdad222** [comment]
میشه به هم نزدیکشون کرد یا با هم تناسب داشته باشند

**Comment by rastikerdar** [comment]
در نسخه های جدید تلاش گردید این هماهنگی بیشتر بشه.
سوراخ ـعـ رو اگر بزرگتر کنم شکل ـعـ به هم میریزه. شاید بهتر باشه کلا حذفش کنم عوضش سایز کل ـعـ رو کوچکتر کنم.

ممنونم بابت گزارش خطا.
