### ISSUE TITLE
ظاهر بد عینهو

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/parastoo-font#3]
بد شده
شاید به دلیل بزرگتر بودن ه نسبت به و 
شاید کانکتورش هم کوتاه هست
![screenshot from 2015-12-30 22 49 39](https://cloud.githubusercontent.com/assets/3942191/12056013/c6807a10-af47-11e5-9a3a-0c907edd4144.png)

**Comment by rastikerdar** [comment]
آره
هم ظاهر عـ باید تغییر کنه هم اتصال ـهـ ـو

**Comment by rastikerdar** [comment]
در ورژن جدید اصلاح شد. متشکرم
