### ISSUE TITLE
پ اول

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/parastoo-font#4]
پا جای نقطه‌هاش خوب نیست
میشه طول پ رو زیاد کرد و نقطه‌هارو برد وسط تر
یا ترکیب پ و ا رو لیگچر کرد و نقطه‌هارو وسط گذاشت
الان که دقت میکنم رو یا هم میشه کارایی کرد
![screenshot from 2015-12-30 22 59 19](https://cloud.githubusercontent.com/assets/3942191/12056176/0c7c5934-af49-11e5-854b-78555afb0d94.png)

**Comment by rastikerdar** [comment]
باید طولشون زیاد بشه.
خیلی خوب کاری کردین که اومدین اینجا توی خود مخزن پرستو ایشو گذاشتین

**Comment by rastikerdar** [comment]
فکر می کنم بهتر شد. هر چند که با ایده آل فاصله زیادی داره. :(
![screenshot from 2016-11-11 01-38-57](https://cloud.githubusercontent.com/assets/3116038/20196390/c91fc68e-a7af-11e6-8cc7-a7c2e98cc067.png)

**Comment by zoghal** [comment]
صابر جان در کلماتی مثل «رپر» حرف ر با نقطه‌ها ممکنه خیلی نزدیک هم بشوند یا اصلا وصل بشنده. اگر با کرنینگ برطرف کنی بین حروف گپ زیادی ایجاد میشه. فونت نازنین به دلیل اینکه برای چاپ سربی تهیه شده مجبور بوده نقاط رو اینطوری قرار بده.

![img_20161111_040401-01](https://cloud.githubusercontent.com/assets/174688/20200161/aa6a5dca-a7c4-11e6-8b5b-db9255f7855c.jpeg)

در تصویر برات نشون دادم که میشه در فونت نقاط رو خارج از حاشیه چپ هم شیفت بردی. چون فضای اشغال یک حرف با اتصالات حرف بعدی کامل میشه . البته در این موارد باید مراقب ‍ی هم باشی. 
تجربه بهم ثابت کرد که جایگاه نقاط در انواع تایپ ها می‌تونه جابجایی محسوسی داشته باشه و نیاز نیست حتما بر اساس آنچه تا الان عمل میشده من هم عمل کنم.

**Comment by rastikerdar** [comment]
متشکرم برای توضیحات و تصویر.
۱. حق با شماست. کرنینگ «ر» با «پ» و «ی» به ویژه توی حالت ضخیم مشکل داره.
۲. دقیقا به خاطر همین ـی اذیت میشم. توی همین نسخه هم خیلی نزدیکه. مگر اینکه ـی رو دورتر بزارم.

**Comment by zoghal** [comment]
اتصال ی رو اضافه کنی اون وقت تو سی  یا کی ممکنه مشکل بخوری خیلی کشیده میشه.
بطور کلی برای حل این مشکل باید با حروف بازی کنی تا به یک تعامل برسی

**Comment by rastikerdar** [comment]
توی نسخه جدید ۲ فکر می‌کنم تا حد زیادی مشکل مرتفع شد. علاوه بر اینکه طول حروف زیاد شد نقطه‌ها نیز به طرف چپ منتقل گردید. با تشکر از شما
![parastoo-peh-yeh](https://user-images.githubusercontent.com/3116038/69763996-27d75480-1184-11ea-96ae-0dc1cbb04f6e.png)
با اجازه ایشو رو می‌بندم
