### ISSUE TITLE
تغییرو یهو سایز دندونه‌ها

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/parastoo-font#5]
این که دندونه‌ها نازک باشه و بعد کلفت شه
یا کلفت باشه و بعد نازک شه
فکر کنم جذاب نیست
البته سلیقه‌ای هست
![screenshot from 2015-12-30 23 03 36](https://cloud.githubusercontent.com/assets/3942191/12056263/bb03e04e-af49-11e5-9e15-954558658bdf.png)
![screenshot from 2015-12-30 23 03 53](https://cloud.githubusercontent.com/assets/3942191/12056278/fb5a8800-af49-11e5-8a4f-5b0c12a4c71a.png)

**Comment by behdad222** [comment]
اینو ببین
کلفت شروع میشه
نازک میشه بعد دوباره کلفت میشه
![screenshot from 2015-12-30 23 07 43](https://cloud.githubusercontent.com/assets/3942191/12056299/38b57d04-af4a-11e5-81ab-7399afd138ec.png)

**Comment by rastikerdar** [comment]
دندونه آخر شین سلیقگی بود. اما کوچکترش میکنم ببینم چطور میشه. البته دندونه ابتدایی مجبوری هست
اون اتصال ـه هم که خیلی افتضاحه! باید اصلاح بشه! :)

ممنونم بابت ایشو

**Comment by rastikerdar** [comment]
در ورژن های جدید اصلاح شد ممونم
