### ISSUE TITLE
نبود فایل وزن سنگین

### ISSUE THREAD

**Issue by masoudgs** [rastikerdar/parastoo-font#6]
با سلام لطفا فایل bold رو اضافه کنید

**Comment by rastikerdar** [comment]
دو تا مشکل وجود داره:
۱. فونت هنوز در حال توسعه است و خرده کاری زیاد داره
۲. استقبالی از فونت نشده شاید به دلیل مشکل اول

نسخه ضخیم این فونت خیلی کار می بره و بدون استقبال عمومی عملا تولیدش توجیهی نداره.

به هر صورت خیلی ممنونم بابت این ایشو. لطفا بزارید باز بمونه تا شاید یه روزی انجام بشه.

**Comment by masoudgs** [comment]
به نظرم انقدر از میترا و نازنین و امثالهم توی نمایش محتوا اصلی استفاده شده که فوق العاده خز شده.
فونت پرستو از خیلی جهات از موارد فعلی موجود بهتره.
یک نظرسنجی داخل تویتر بگذارید اونجا هم نظر مردم رو بپرسید بد نیست.
سپاس از زحماتتون.

**Comment by rastikerdar** [comment]
وزن سنگین هم به فونت اضافه شد. 
[rastikerdar.github.io/parastoo-font](http://rastikerdar.github.io/parastoo-font/)

بابت ایشو از شما ممنونم.

**Comment by masoudgs** [comment]
ممنون از زحماتت. به نظرم یه مشکل وجود داره توی وزن سنگین.
معمولا یکی از ویژگی های وزن سنگین افزایش طول یک پاراگراف هست.
اما توی تصویر زیر از طول پاراگراف با وزن سنگین کم میشه.
من چند تا قلم دیگه حتی انگلیسی هم تست زدم قضیه برعکس بود و به طول پاراگراف اضافه میشد.
![screenshot from 2016-03-22 12-06-51](https://cloud.githubusercontent.com/assets/11756815/13944891/baab9ccc-f026-11e5-83ec-0c191e44d9b0.png)
![screenshot from 2016-03-22 12-07-36](https://cloud.githubusercontent.com/assets/11756815/13944892/bab1d3da-f026-11e5-9c47-51fb122e89db.png)

**Comment by zoghal** [comment]
@msudgh نه مسعود جان افزایش طول پاراگراف در بعضی حالات نیاز نیست مخصوص دو یا سه وزن باشه.
مثلا یک تایپ فیس در وزن ریگولار می‌تونه کشیدگی زیادی در سطح یا  در ضخامت اصلی حرف داشته باشه و در وزن بلدش بدون تغییر طول حروف فقط فضای سیاه یا همون هیکل حروف تنگتر میشه..
بستگی به نوع و سبک طراحی بر میگرده.

**Comment by rastikerdar** [comment]
توی نسخه جدید پرستو طول وزن سنگین حروف فارسی با وزن معمولی دقیقا یکی هست. البته نمی دونم با توجه به تایپ فیس پرستو این شیوه صحیح هست یا خیر. توی فونت نازنین وزن سنگینش به طور قابل توجهی بزرگ تر میشه اما احساس کردم برای پرستو شاید نیازی نباشه.

**Comment by masoudgs** [comment]
من فک می‌کردم که افزایش یا کاهش طول یه استاندارد طراحی باشه اما خوب با توضیحاتی که صالح داد میشه گفت دلخواه هست و به سبک تایپ فیس برمیگرده.

**Comment by zoghal** [comment]
من افزایش طول پاراگراف رو گفتم. کاهش طول پارگراف در وزن بلد به عقیده من یک مشکل هست!
