### ISSUE TITLE
گلیف میم

### ISSUE THREAD

**Issue by masoudgs** [rastikerdar/parastoo-font#7]
![capture](https://cloud.githubusercontent.com/assets/11756815/12195719/7ef39740-b60e-11e5-870a-8b88950e83d0.PNG)
گلیف میم به نظرم از نظر ضخامت و شکل هماهنگی کافی با باقی گلیف ها رو نداره.

**Comment by rastikerdar** [comment]
کاملا حق با شماست
توی ورژن جدید این شکلیش کردم. نمی دونم بهتر شده یا نه؟

![screenshot from 2016-01-08 16-02-09](https://cloud.githubusercontent.com/assets/3116038/12197985/4d82ae36-b621-11e5-8b61-4f35582bf4bd.png)

**Comment by rastikerdar** [comment]
البته فکر کنم این یکی بهتره باشه:
![screenshot from 2016-01-08 16-14-11](https://cloud.githubusercontent.com/assets/3116038/12198193/f4ab3308-b622-11e5-8236-2da42717145e.png)

**Comment by masoudgs** [comment]
اخری مناسبه
اما انتهاش رو باریک تر کنید شاید تناسب بهتری داشته باشه
یه نکته دیگه اینکه خمیدگی که بین خط انتهایی میم کمتر بشه فک کنم قشنگ تر میشه

**Comment by zoghal** [comment]
صابر جان شانه میم چشم  و حلقه رو بکش بالاتر بهتر میشه.

**Comment by rastikerdar** [comment]
اینطوری منظورتونه؟
![screenshot from 2016-01-15 16-28-13](https://cloud.githubusercontent.com/assets/3116038/12353522/11fbd840-bba5-11e5-9784-c379ad59677b.png)

**Comment by masoudgs** [comment]
خیلی عالی شده.

**Comment by zoghal** [comment]
احسنتم، خداییش عجوبی‌ای حسودیم شد بهت :+1:
