### ISSUE TITLE
شکل لا

### ISSUE THREAD

**Issue by masoudgs** [rastikerdar/parastoo-font#8]
سلام
اگر دقت کنید الف در لیگچر لا زیاد براش جالب نیست
شاید اگر الف مقداری به سمت چپ بیاد بهتر بشه و مقداری هم ساعتگرد بچرخه(20 درجه) بد نباشه
![screenshot from 2016-01-19 15-49-19](https://cloud.githubusercontent.com/assets/11756815/12418394/4d3768da-bec4-11e5-8ce2-a14f4e92d266.png)

**Comment by rastikerdar** [comment]
البته توی نسخه قبلی شکل لا عوض شده. نمی دونم بهتر شده با نه. هرچند که هنوز خرده کاری داره. اگر فکر می کنید خوب نیست عوضش کنم.
![screenshot from 2016-01-19 17-33-23](https://cloud.githubusercontent.com/assets/3116038/12420623/043566d2-bed3-11e5-9641-ddb64e6efe14.png)

**Comment by masoudgs** [comment]
به نظرم پایین الف چاق تر بشتر بهتره

**Comment by zoghal** [comment]
صابر جان تو()  تو س‍ دندانه دوم نزدیک دندانه اول باید باشه.
الان خوبه.
اما دندانه سوم باید کمی فاصله اش از دندانه دوم بیشتر باشه.

**Comment by rastikerdar** [comment]
الف رو چسباندم به زمینه. ممنونم آقای قربانی

صالح جان فاصله دندونه سوم رو هم بیشتر کردم. متشکرم
