### ISSUE TITLE
بهینه سازی اندازه فونت

### ISSUE THREAD

**Issue by sIiiS** [rastikerdar/parastoo-font#9]
ممنون از زحماتی که می کشید
به نظر میاد اندازه فونت در حروف فارسی با حروف انگلیسی کمی متفاوت هست

مثلا من وقتی تست کردم دیدم در اندازه ۱۰ حروف فارسی کوچک تر از حروف انگلیسی در اندازه ۱۰ هستند

اگر امکانش هست کمی متعادل تر بشه چون جاهایی که اندازه ۱۰ به کار رفته، فونت خیلی ریز دیده میشه

**Comment by rastikerdar** [comment]
تشکر می کنم بابت ایشو
خب اندازه فونت رو توی نسخه جدید بیشتر کردم اما حقیقتش بیشتر از این دیگه نتونستم. تلاش کردم که با لاتین هماهنگ بشه.
جدا کننده ارقام رو هم به پایین منتقل کردم.

باز هم مشکلی بود ممنون میشم در جریان بگذارید.

**Comment by sIiiS** [comment]
بسیار ممنون از همکاری شما و احساس مسئولیتی که دارید

**Comment by rastikerdar** [comment]
من عذرخواهی می کنم از اینکه باید اعلام کنم باز هم سایز قلم بزرگتر شد.
همچنین نسخه توپر یا بولد قلم هم اضافه شد.
